//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KutuphaneVeriTabaniEntities : DbContext
    {
        public KutuphaneVeriTabaniEntities()
            : base("name=KutuphaneVeriTabaniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calisanlar> Calisanlar { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Kitap> Kitap { get; set; }
        public virtual DbSet<Kutuphane> Kutuphane { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uyeler> Uyeler { get; set; }
        public virtual DbSet<Yayinevi> Yayinevi { get; set; }
        public virtual DbSet<Yazarlar> Yazarlar { get; set; }
        public virtual DbSet<Emanet> Emanet { get; set; }
        public virtual DbSet<Kitap_Kategori> Kitap_Kategori { get; set; }
        public virtual DbSet<Kitap_Yayinevi> Kitap_Yayinevi { get; set; }
        public virtual DbSet<Kutuphane_Uye> Kutuphane_Uye { get; set; }
    }
}
